version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: uppa
      POSTGRES_PASSWORD: < DB_PASSWORD >
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: uppa3/djangoweather:1.0.1
    restart: unless-stopped
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY='< YOUR_DJANGO_KEY >'
      - DEBUG_MODE=True
      - DB_NAME=weather_db
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=uppa
      - DB_PASSWORD=< DB_PASSWORD >

volumes:
  postgres_data:
